"""Phase 2 · Step 1 — run the whole cleaning + feature pipeline in the agreed build order.

Usage (from the project folder):
    python run_pipeline.py

Reads the raw CSVs in "Data Source/", writes clean tables to data/processed/
and a pass/fail report of every Phase 1 check to reports/cleaning_check_report.md.
"""
import time

from src import config as C
from src import load, clean_daily, clean_hourly, clean_sleep, clean_weight, clean_heart, features, checks


def main():
    t0 = time.time()
    C.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    C.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    steps = {}

    print("1  Loading raw files …")
    daily_raw = load.load_daily()
    hourly_raw = load.load_hourly()
    steps["hourly_raw"] = len(hourly_raw)
    sleep_day_raw = load.load_sleep_day()
    minute_sleep_raw = load.load_minute_sleep()
    weight_raw = load.load_weight()
    print("   loading heart rate (2.5 M rows) …")
    hr_raw = load.load_heartrate()

    print("2  Movement hours from the hourly table")
    mh = clean_daily.movement_hours(hourly_raw)

    print("3  wear_log (before anything is removed)")
    wear_log = clean_daily.build_wear_log(daily_raw, mh)

    print("4  Cleaning dailyActivity (P2 → P3 → P4 → P7 → P11)")
    daily, steps["daily"] = clean_daily.clean_daily(daily_raw, mh)

    print("5  Sleep: minute detail → sessions → nights")
    sleep_nights, sleep_sessions = clean_sleep.build_sleep_nights(sleep_day_raw, minute_sleep_raw)

    print("6  Sleep flags on daily (P5)")
    daily = clean_daily.add_sleep_flags(daily, sleep_nights)

    print("7  Hourly → valid days only")
    hourly = clean_hourly.clean_hourly(hourly_raw, daily)

    print("8  Weight")
    weight = clean_weight.clean_weight(weight_raw)
    body = clean_weight.user_body_profile(weight)

    print("9  Heart rate → daily summary")
    hr_daily, steps["heart"] = clean_heart.daily_heart_rate(hr_raw, daily)

    print("10 daily_master + user_profile")
    daily_master = features.build_daily_master(daily, sleep_nights, hr_daily)
    profile = features.build_user_profile(daily_raw, daily, wear_log, hourly, sleep_nights, sleep_day_raw, body, hr_daily, hr_raw["Id"].unique())

    tables = {"daily_clean": daily, "wear_log": wear_log, "hourly_clean": hourly, "sleep_nights": sleep_nights,
              "sleep_sessions": sleep_sessions, "weight_logs_clean": weight, "user_body_profile": body,
              "daily_heart_rate": hr_daily, "daily_master": daily_master, "user_profile": profile}
    for name, df in tables.items():
        df.to_csv(C.PROCESSED_DIR / f"{name}.csv", index=False)

    print("11 Running every Phase 1 check")
    chk = checks.run_all(tables, steps)
    tab = chk.table()
    n_pass, n_all = int(tab["pass"].sum()), len(tab)
    sizes = "\n".join(f"| `{k}.csv` | {len(v):,} | {v.shape[1]} |" for k, v in tables.items())
    report = (f"# Cleaning check report\n\n**{n_pass} of {n_all} checks passed** · generated by `run_pipeline.py` "
              f"in {time.time() - t0:.0f} s\n\n## Output tables\n\n| File | Rows | Columns |\n|---|---|---|\n{sizes}\n\n"
              f"## Checks (refs point to the Cleaning Notes)\n\n{chk.markdown()}\n")
    (C.REPORTS_DIR / "cleaning_check_report.md").write_text(report, encoding="utf-8")
    print(f"\nDone in {time.time() - t0:.0f} s — {n_pass}/{n_all} checks passed")
    failed = tab[~tab["pass"]]
    if len(failed):
        print("\nFAILED CHECKS:")
        print(failed.to_string(index=False))
    return tables, chk


if __name__ == "__main__":
    main()
